### ISSUE TITLE
Does not compile on Node v8.12.0, Windows 10 1803

### ISSUE THREAD

**Issue by Luxray5474** [creationix/node-gamepad#21]
Tried installing it, had to install `windows-build-tools`, and now the problem I get is: 

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\skybl\Documents\#Programming\XBXctrl\node_modules\gamepad
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN xbxctrl@1.0.0 No description
npm WARN xbxctrl@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gamepad@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gamepad@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\skybl\AppData\Roaming\npm-cache\_logs\2018-09-16T17_26_43_340Z-debug.log
```

Why is it looking for its files on the root of my disk? Is there any way to fix it and make it compile? Thanks

**Comment by Luxray5474** [comment]
Fixed the issue, it was looking for its files at the root of my disk because the environment variable `VCTargetsPath` wasn't set at all. 

# FIX:
 
1. Open `regedit` and navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\4.0`
2. Edit or create a **string** named `VCTargetsPath` and set its value to `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140` which is the path to the needed files.
3. Close it down, and open Powershell **in administrator mode**.
4. Enter the command `SET VCTargetsPath="C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140"`. That sets said environment variable to the path. 
5. Reboot.
