### ISSUE TITLE
Error: gamepad@1.6.0 install: `prebuild-install || node-gyp rebuild`

### ISSUE THREAD

**Issue by renatonerijr** [creationix/node-gamepad#27]
System: Linux Mint (x86), Tried also in Ubuntu 19.04 and got same error
Node version: using node v12.15.0 (npm v6.13.6) 

Error Log from npm:
```log
gyp ERR! build error

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/neo/Documentos/Workspace/RetroAct/node_modules/gamepad
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.17 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux",
"arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gamepad@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gamepad@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/neo/.npm/_logs/2020-02-12T19_11_53_462Z-debug.log
```

**Comment by renatonerijr** [comment]
Turns out that I did not have g++
This fixed the issue:
https://unix.stackexchange.com/questions/140350/linux-g-command-not-found

But this is still has this error: 
```
module.exports = response => {
                          ^^

SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/neo/Documentos/Workspace/Nodejs/Retro/RetroBigPicture-TMP-/node_modules/gamepad/node_modules/prebuild-install/node_modules/simple-get/index.j
s:8:26)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
```

**Comment by creationix** [comment]
> node -v v3.3.1

> SyntaxError: Unexpected token =>

You're running an old version of node.js that doesn't support arrow functions.  Are you able to update?

**Comment by creationix** [comment]
Yeah, the log doesn't match the stated version at all:

> Node version: using node v9.11.2 (npm v5.6.0) // Using Node Version Manager

vs

> npm ERR! argv "/home/neo/.nvm/versions/io.js/v3.3.1/bin/iojs" "/home/neo/.nvm/versions/io.js/v3.3.1/bin/npm" "install" "gamepad"
> npm ERR! node v3.3.1
> npm ERR! npm  v2.14.3

**Comment by renatonerijr** [comment]
I edited the log, and the description sorry for that

**Comment by renatonerijr** [comment]
I'm trying to use node 12 because I need to use node-gamepad with electron, and I got this error when trying to run with node 10, I think I got this problem because electron don't use node from my path
```log
App threw an error during load
[1] Error: The module '/home/neo/Documentos/Workspace/RetroAct/node_modules/gamepad/build/Release/gamepad.node'
[1] was compiled against a different Node.js version using
[1] NODE_MODULE_VERSION 64. This version of Node.js requires
[1] NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
[1] the module (for instance, using `npm rebuild` or `npm install`).
[1]     at process.func (electron/js2c/asar.js:140:31)
[1]     at process.func [as dlopen] (electron/js2c/asar.js:140:31)
[1]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
[1]     at Object.func (electron/js2c/asar.js:140:31)
[1]     at Object.func [as .node] (electron/js2c/asar.js:140:31)
[1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[1]     at Module._load (internal/modules/cjs/loader.js:728:14)
[1]     at Module._load (electron/js2c/asar.js:717:26)

[1]     at Function.Module._load (electron/js2c/asar.js:717:26)
[1]     at Module.require (internal/modules/cjs/loader.js:853:19)
[0] Compiled successfully!
```

**Comment by renatonerijr** [comment]
@creationix I Update the log running with Node 12
