### ISSUE TITLE
Build fails on linux

### ISSUE THREAD

**Issue by GameKyuubi** [creationix/node-gamepad#29]
```
../binding.cc: At global scope:
../binding.cc:115:6: error: variable or field ‘init’ declared void
  115 | void init(Handle<Object> target) {
      |      ^~~~
```
---
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.7.6-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok 
```

building on archlinux via `yarn add`.  someone knows what's up?

**Comment by jeffbdavenport** [comment]
I'm having the same issue on Ubuntu with `npm start`

```
../binding.cc: At global scope:
../binding.cc:115:11: error: variable or field ‘init’ declared void
  115 | void init(Handle<Object> target) {
      |           ^~~~~~
../binding.cc:115:11: error: ‘Handle’ was not declared in this scope
../binding.cc:115:24: error: expected primary-expression before ‘>’ token
  115 | void init(Handle<Object> target) {
      |                        ^
../binding.cc:115:26: error: ‘target’ was not declared in this scope
  115 | void init(Handle<Object> target) {
      |                          ^~~~~~
In file included from ../binding.cc:1:
../binding.cc:135:22: error: ‘init’ was not declared in this scope; did you mean ‘int’?
  135 | NODE_MODULE(gamepad, init)
      |                      ^~~~
```

**Comment by jeffbdavenport** [comment]
@GameKyuubi If you pull in the most recent changes to bindings.cc it builds just fine for me. Guess the changes haven't been published yet

**Comment by manouman** [comment]
After cloning the repo and installing the packages I haven't any error but, if I want to add gamepad to an existent project I have the same error that @GameKyuubi has.

I just fixed the same error downgrading the node version of my project to v10.
